export default {
  pagination: {
    enabled: true,
    position: 'top', // one of ['top', 'bottom', 'top-bottom'],
    perPage: 10,
    pageRange: 3,
    prevText: 'Previous',
    nextText: 'Next',
    breakViewText: '...',
    firstLastButton: true,
    firstButtonText: '<<',
    lastButtonText: '>>',
    hidePrevNext: false,
    infoEnabled: true,
    infoPosition: 'top',
    infoTemplate: 'Displaying :from..:to of :total entries',
  },
  noDataText: 'No data to display',
  sorting: {
    enabled: true,
    multipleColumnsSorting: true,
    defaultSortingColumns: {},
  },
  filtering: true,
  selection: true,
  idField: null,
  axios: {},
  responsive: {
    enabled: true,
    breakpoint: 1023,
  },
  additionalRowClassHandler: () => '',
  styling: {
    containerClass: 'r-grid',
    contentClass: 'r-grid__content',
    contentLoadingClass: 'grid--wrapper--content--loading',
    tableWrapperClass: 'r-grid__table-wrapper',
    tableClass: 'r-grid__table',
    tableHeadClass: 'r-grid__table-head',
    tableRowClass: 'r-grid__table-row',
    tableRowExpandedClass: 'r-grid__table-row-expanded',
    tableRowSelectedClass: 'r-grid__table-row-selected',
    tableHeadCellClass: 'r-grid__table-head-cell',
    tableHeadHolderClass: 'r-grid__table-head-holder',
    tableBodyClass: 'r-grid__table-body',
    tableBodyCellClass: 'r-grid__table-body-cell',
    tableBodyCellExpandedClass: 'r-grid__table-body-cell-expanded',
    cardWrapperClass: 'r-grid__cards-wrapper',
    cardControlsClass: 'r-grid__cards-controls',
    cardColumnClass: 'r-grid__card-col',
    cardClass: 'r-grid__card',
    cardExpandedClass: 'r-grid__card-expanded',
    cardSelectedClass: 'r-grid__card-selected',
    cardRowClass: 'r-grid__card-row',
    cardLabelClass: 'r-grid__card-label',
    cardValueClass: 'r-grid__card-value',
    cardValueExpandedClass: 'r-grid__card-value-expanded',
    pagination: {
      infoClassTop: 'r-grid__pagination-info r-grid__pagination-info--top',
      infoClassBottom: 'r-grid__pagination-info r-grid__pagination-info--bottom',
      containerClass: 'r-grid__pagination',
      pageClass: 'r-grid__pagination-page',
      pageLinkClass: 'r-grid__pagination-link',
      prevClass: 'r-grid__pagination-prev',
      prevLinkClass: 'r-grid__pagination-prev-link',
      nextClass: 'r-grid__pagination-next',
      nextLinkClass: 'r-grid__pagination-next-link',
      breakViewClass: 'r-grid__pagination-break-view',
      breakViewLinkClass: 'r-grid__pagination-break-view-link',
    },
  },
};
